// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailly.ShopService.Infrastructure.DataAccess;

#nullable disable

namespace Tailly.ShopService.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260510102946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"SessionId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderAddresses");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CompletionEmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PickupPointId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecipientFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PickupPointId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Pickup.PickupPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EstimatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PickupPoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8a2ebd1-2799-4f19-a8d2-4cb6bfef4782"),
                            Address = "Москва, ул. Тверская, 12, стр. 1",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6349),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Тверской"
                        },
                        new
                        {
                            Id = new Guid("f20f7832-3493-4b6d-95d3-8232d975aa0b"),
                            Address = "Москва, ул. Братиславская, 21, корп. 2",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6354),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Марьино"
                        },
                        new
                        {
                            Id = new Guid("7128b4a2-f5ce-4a6d-b6b2-0e8fa3ca7baf"),
                            Address = "Москва, Ленинский проспект, 45",
                            EstimatedDate = new DateTime(2026, 5, 12, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6356),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Ленинском проспекте"
                        },
                        new
                        {
                            Id = new Guid("79bdfa43-3f64-4ce3-9f12-4b187393f3e9"),
                            Address = "Москва, г. Химки, ул. Ленинградская, 29",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6357),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Химках"
                        },
                        new
                        {
                            Id = new Guid("440e5231-7206-4f6e-bbf5-283ba66d73f4"),
                            Address = "Москва, проспект Мира, 119, стр. 23",
                            EstimatedDate = new DateTime(2026, 5, 12, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6359),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на ВДНХ"
                        },
                        new
                        {
                            Id = new Guid("a112ef56-9db3-4445-951b-199772cad332"),
                            Address = "Санкт-Петербург, Невский проспект, 56",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6360),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Невском"
                        },
                        new
                        {
                            Id = new Guid("b9180c49-1885-4f0c-8db3-00ecabf01494"),
                            Address = "Санкт-Петербург, ул. Будапештская, 18",
                            EstimatedDate = new DateTime(2026, 5, 12, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6362),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Купчино"
                        },
                        new
                        {
                            Id = new Guid("edbd7e63-a832-4abf-a5c7-59e0270ea53c"),
                            Address = "Санкт-Петербург, Московский проспект, 183",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6365),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Московском проспекте"
                        },
                        new
                        {
                            Id = new Guid("84cb09a5-1776-4834-bb7a-683ea8b9c1f4"),
                            Address = "Санкт-Петербург, пр. Испытателей, 15",
                            EstimatedDate = new DateTime(2026, 5, 12, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6367),
                            Provider = 1,
                            Title = "ПВЗ СДЭК у станции метро Пионерская"
                        },
                        new
                        {
                            Id = new Guid("bc6f69ec-d710-4860-8ac6-27b6e1a8efbb"),
                            Address = "Екатеринбург, ул. Малышева, 51",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6368),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Малышева"
                        },
                        new
                        {
                            Id = new Guid("a5867f95-8a76-45cd-95a0-4c3ec06f7362"),
                            Address = "Екатеринбург, ул. Космонавтов, 11/1",
                            EstimatedDate = new DateTime(2026, 5, 12, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6370),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Уралмаше"
                        },
                        new
                        {
                            Id = new Guid("cc8f568f-24f7-4599-b674-6646a1c7c469"),
                            Address = "Новосибирск, Красный проспект, 52",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6371),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Красном проспекте"
                        },
                        new
                        {
                            Id = new Guid("e32baa7e-13d1-4d4f-ae5d-6dd240c9c72e"),
                            Address = "Новосибирск, ул. Ильича, 10",
                            EstimatedDate = new DateTime(2026, 5, 13, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6373),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Академгородке"
                        },
                        new
                        {
                            Id = new Guid("0be164bd-10d3-4975-81ac-254b49fafe9d"),
                            Address = "Казань, ул. Баумана, 27",
                            EstimatedDate = new DateTime(2026, 5, 11, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6375),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Баумана"
                        },
                        new
                        {
                            Id = new Guid("34d8aa41-aca8-4290-b493-03605c4f0c7c"),
                            Address = "Казань, пр. Победы, 74",
                            EstimatedDate = new DateTime(2026, 5, 12, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6376),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Советском районе"
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Slug = "food",
                            Title = "Корм и лакомства"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Slug = "toys",
                            Title = "Игрушки и развлечения"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Slug = "accessories",
                            Title = "Аксессуары и одежда"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Slug = "grooming",
                            Title = "Груминг и уход"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Slug = "health",
                            Title = "Здоровье и витамины"
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForWhom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PetSize")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Price");

                    b.HasIndex("Rating");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b3647bc-92bd-483f-9aa4-d20130a619a9"),
                            Brand = "Royal Canin",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CountryOfOrigin = "Франция",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6018),
                            Description = "Премиальный полнорационный корм для собак старше 1 года. Поддерживает иммунитет и здоровье пищеварения.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Сухой корм",
                            OldPrice = 2790m,
                            PetSize = "Все размеры",
                            Price = 2490m,
                            Purpose = "Ежедневное питание",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Сухой корм для взрослых собак",
                            Slug = "royal-canin-adult-dog",
                            StockQuantity = 87,
                            Title = "Royal Canin Adult Dog Food",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6018)
                        },
                        new
                        {
                            Id = new Guid("81acec04-ac74-4f06-861a-261b64eaae85"),
                            Brand = "Whiskas",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CountryOfOrigin = "Россия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6024),
                            Description = "Нежные кусочки в соусе. Идеальный рацион для взрослых кошек.",
                            ForWhom = "Кошки",
                            IsAvailable = true,
                            Material = "Влажный корм",
                            PetSize = "Все размеры",
                            Price = 89m,
                            Purpose = "Ежедневное питание",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Влажный корм для кошек",
                            Slug = "whiskas-wet-chicken",
                            StockQuantity = 320,
                            Title = "Whiskas Wet Cat Food с курицей",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6024)
                        },
                        new
                        {
                            Id = new Guid("a9ebd856-d30c-4f8b-8ed2-3ec918a0f865"),
                            Brand = "Pedigree",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CountryOfOrigin = "Россия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6029),
                            Description = "Сбалансированное питание для правильного роста и развития щенков.",
                            ForWhom = "Щенки",
                            IsAvailable = true,
                            Material = "Сухой корм",
                            OldPrice = 2190m,
                            PetSize = "Все размеры",
                            Price = 1890m,
                            Purpose = "Рост и развитие",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Корм для щенков всех пород",
                            Slug = "pedigree-puppy",
                            StockQuantity = 64,
                            Title = "Pedigree Puppy для щенков",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6029)
                        },
                        new
                        {
                            Id = new Guid("d7a9090a-6d01-4a36-9e9d-2fd9fef935a4"),
                            Brand = "Brit Care",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CountryOfOrigin = "Чехия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6040),
                            Description = "Гипоаллергенный корм для собак с чувствительным пищеварением.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Сухой корм",
                            PetSize = "Все размеры",
                            Price = 3190m,
                            Purpose = "Гипоаллергенное питание",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Беззерновой корм с лососем",
                            Slug = "brit-care-salmon",
                            StockQuantity = 45,
                            Title = "Brit Care Grain-Free Salmon",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6040)
                        },
                        new
                        {
                            Id = new Guid("f2539156-ab5d-4f0a-b542-dc9cc37c3239"),
                            Brand = "Bosch",
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CountryOfOrigin = "Германия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6044),
                            Description = "Полезные косточки и палочки для поощрения.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Лакомства",
                            OldPrice = 590m,
                            PetSize = "Все размеры",
                            Price = 450m,
                            Purpose = "Поощрение и тренировка",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Натуральные лакомства",
                            Slug = "bosch-dog-treats",
                            StockQuantity = 210,
                            Title = "Лакомство для собак Bosch",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6045)
                        },
                        new
                        {
                            Id = new Guid("3461d3bf-6549-4049-beb0-4651ab3a4f62"),
                            Brand = "SmartPet",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6049),
                            Description = "Автоматический мячик с несколькими режимами движения.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Пластик",
                            OldPrice = 1590m,
                            PetSize = "Средний/Крупный",
                            Price = 1290m,
                            Purpose = "Активные игры",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Умная игрушка с движением",
                            Slug = "interactive-dog-ball",
                            StockQuantity = 42,
                            Title = "Интерактивный мяч для собак",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6050)
                        },
                        new
                        {
                            Id = new Guid("c7b91735-1896-4dae-8b03-cfe3b90813f0"),
                            Brand = "PlayCat",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6054),
                            Description = "Лёгкая удочка с яркими перьями.",
                            ForWhom = "Кошки",
                            IsAvailable = true,
                            Material = "Перья + пластик",
                            PetSize = "Все размеры",
                            Price = 490m,
                            Purpose = "Охота и активность",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Любимая игрушка кошек",
                            Slug = "cat-feather-wand",
                            StockQuantity = 95,
                            Title = "Дразнилка с перьями для кошек",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6055)
                        },
                        new
                        {
                            Id = new Guid("cbc1ac00-2283-45d3-b33e-0a7f1373ae2c"),
                            Brand = "FunToys",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6059),
                            Description = "Прочный плюш с пищалкой внутри.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Плюш",
                            OldPrice = 1190m,
                            PetSize = "Маленький/Средний",
                            Price = 890m,
                            Purpose = "Перетягивание и жевание",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Мягкая пищащая игрушка",
                            Slug = "squeaky-plush-bear",
                            StockQuantity = 67,
                            Title = "Пищащий плюшевый медведь",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6060)
                        },
                        new
                        {
                            Id = new Guid("9dac461d-d71a-4420-967f-dc397994f358"),
                            Brand = "LaserPet",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6064),
                            Description = "Классическая лазерная указка.",
                            ForWhom = "Кошки",
                            IsAvailable = true,
                            Material = "Пластик",
                            PetSize = "Все размеры",
                            Price = 390m,
                            Purpose = "Физическая и умственная нагрузка",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Лазер для активных игр",
                            Slug = "cat-laser-pointer",
                            StockQuantity = 180,
                            Title = "Лазерная указка для кошек",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6064)
                        },
                        new
                        {
                            Id = new Guid("538fe373-3572-4dd1-b068-f923543f77d9"),
                            Brand = "StrongDog",
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6069),
                            Description = "Прочный канат для игр с собакой.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Хлопковый канат",
                            OldPrice = 890m,
                            PetSize = "Средний/Крупный",
                            Price = 690m,
                            Purpose = "Перетягивание",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Крепкий канат",
                            Slug = "rope-tug-toy",
                            StockQuantity = 53,
                            Title = "Канатная игрушка для перетягивания",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6069)
                        },
                        new
                        {
                            Id = new Guid("a3746572-16ff-4cf3-af67-0b8673bffcf7"),
                            Brand = "ComfortWalk",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6073),
                            Description = "Мягкая и удобная шлейка для средних и крупных собак.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Нейлон + флис",
                            PetSize = "Средний/Крупный",
                            Price = 1690m,
                            Purpose = "Выгул",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Комфортная шлейка",
                            Slug = "adjustable-dog-harness",
                            StockQuantity = 28,
                            Title = "Регулируемая шлейка для собак",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6073)
                        },
                        new
                        {
                            Id = new Guid("37083c6d-2711-44de-90a0-b0bf2684dcba"),
                            Brand = "ProLeash",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6078),
                            Description = "Надёжный нейлоновый поводок для крупных собак.",
                            ForWhom = "Собаки",
                            IsAvailable = false,
                            Material = "Нейлон",
                            OldPrice = 1490m,
                            PetSize = "Крупный",
                            Price = 1290m,
                            Purpose = "Выгул",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Прочный поводок",
                            Slug = "xl-nylon-leash",
                            StockQuantity = 33,
                            Title = "Поводок нейлоновый XL",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6078)
                        },
                        new
                        {
                            Id = new Guid("3080a42d-ab57-414e-8925-82775c1de349"),
                            Brand = "WinterPet",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6082),
                            Description = "Утеплённый комбинезон с капюшоном.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Полиэстер + синтепон",
                            OldPrice = 2590m,
                            PetSize = "Средний/Крупный",
                            Price = 2190m,
                            Purpose = "Защита от холода",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Зимняя одежда для собак",
                            Slug = "warm-dog-jumpsuit",
                            StockQuantity = 19,
                            Title = "Теплый комбинезон для собак",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6083)
                        },
                        new
                        {
                            Id = new Guid("ea88eab3-06a9-4614-80f9-dd8d457a498d"),
                            Brand = "CeramicPet",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6087),
                            Description = "Керамическая миска с резиновым основанием.",
                            ForWhom = "Собаки/Кошки",
                            IsAvailable = true,
                            Material = "Керамика + резина",
                            PetSize = "Все размеры",
                            Price = 790m,
                            Purpose = "Кормление",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Устойчивая миска",
                            Slug = "ceramic-non-slip-bowl",
                            StockQuantity = 124,
                            Title = "Миска керамическая антискользящая",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6087)
                        },
                        new
                        {
                            Id = new Guid("23746c5a-0e90-4e6a-b902-445f92756b98"),
                            Brand = "SmartTrack",
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6092),
                            Description = "Ошейник с GPS и отслеживанием активности.",
                            ForWhom = "Собаки",
                            IsAvailable = false,
                            Material = "Нейлон",
                            OldPrice = 3990m,
                            PetSize = "Средний/Крупный",
                            Price = 3490m,
                            Purpose = "Отслеживание местоположения",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Умный ошейник",
                            Slug = "gps-pet-collar",
                            StockQuantity = 12,
                            Title = "Ошейник с GPS-трекером",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6092)
                        },
                        new
                        {
                            Id = new Guid("ba872d50-5c81-40d4-954e-0ecdb0916efb"),
                            Brand = "PurePet",
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CountryOfOrigin = "Россия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6158),
                            Description = "Натуральный шампунь с экстрактом алоэ.",
                            ForWhom = "Собаки",
                            IsAvailable = false,
                            Material = "Жидкий шампунь",
                            OldPrice = 990m,
                            PetSize = "Все размеры",
                            Price = 790m,
                            Purpose = "Гигиена шерсти",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Гипоаллергенный шампунь",
                            Slug = "dog-shampoo-aloe",
                            StockQuantity = 47,
                            Title = "Шампунь для собак с алоэ",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6158)
                        },
                        new
                        {
                            Id = new Guid("6b729cb8-c2dd-4ccf-89b3-05eed1d16c9b"),
                            Brand = "GroomPro",
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6163),
                            Description = "Профессиональный когтерез с ограничителем.",
                            ForWhom = "Собаки/Кошки",
                            IsAvailable = true,
                            Material = "Нержавеющая сталь",
                            PetSize = "Все размеры",
                            Price = 690m,
                            Purpose = "Уход за когтями",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Безопасный когтерез",
                            Slug = "pet-nail-clipper",
                            StockQuantity = 55,
                            Title = "Когтерез для животных",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6163)
                        },
                        new
                        {
                            Id = new Guid("3be4a5fa-fd45-453d-bbf9-1f314b747ff2"),
                            Brand = "FurCare",
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6168),
                            Description = "Удобная щётка для удаления выпавшей шерсти.",
                            ForWhom = "Кошки",
                            IsAvailable = true,
                            Material = "Пластик + металл",
                            OldPrice = 790m,
                            PetSize = "Все размеры",
                            Price = 590m,
                            Purpose = "Уход за шерстью",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Щётка с самоочисткой",
                            Slug = "self-cleaning-cat-brush",
                            StockQuantity = 68,
                            Title = "Самоочищающаяся щетка для кошек",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6168)
                        },
                        new
                        {
                            Id = new Guid("6d861eaf-a99e-4342-bbe2-c1529376bf06"),
                            Brand = "CleanPaw",
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CountryOfOrigin = "Россия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6172),
                            Description = "Быстрое очищение шерсти без купания.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Сухой порошок",
                            PetSize = "Все размеры",
                            Price = 890m,
                            Purpose = "Сухое очищение",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Сухой шампунь без воды",
                            Slug = "dry-dog-shampoo",
                            StockQuantity = 82,
                            Title = "Сухой шампунь для собак",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6172)
                        },
                        new
                        {
                            Id = new Guid("60a0315b-ebe9-46e4-b56e-acae29a356b6"),
                            Brand = "DentalCare",
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CountryOfOrigin = "Китай",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6177),
                            Description = "Полный набор для ухода за зубами.",
                            ForWhom = "Собаки/Кошки",
                            IsAvailable = true,
                            Material = "Пластик + металл",
                            OldPrice = 1490m,
                            PetSize = "Все размеры",
                            Price = 1290m,
                            Purpose = "Гигиена зубов",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Гигиена полости рта",
                            Slug = "pet-dental-kit",
                            StockQuantity = 37,
                            Title = "Набор для чистки зубов питомцам",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6177)
                        },
                        new
                        {
                            Id = new Guid("065f9a01-157f-4c29-9743-c9b1a562562d"),
                            Brand = "JointVet",
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CountryOfOrigin = "Германия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6181),
                            Description = "Комплекс для укрепления суставов и хрящей.",
                            ForWhom = "Собаки",
                            IsAvailable = true,
                            Material = "Таблетки",
                            OldPrice = 1790m,
                            PetSize = "Средний/Крупный",
                            Price = 1490m,
                            Purpose = "Здоровье суставов",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Поддержка суставов",
                            Slug = "joint-supplement-dogs",
                            StockQuantity = 51,
                            Title = "Витамины для суставов собак",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6182)
                        },
                        new
                        {
                            Id = new Guid("73db2a59-d927-4060-ab4a-a71a4ebd7f80"),
                            Brand = "ParasiteGuard",
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CountryOfOrigin = "Россия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6186),
                            Description = "Капли на холку от блох и клещей.",
                            ForWhom = "Кошки",
                            IsAvailable = true,
                            Material = "Капли",
                            PetSize = "Все размеры",
                            Price = 890m,
                            Purpose = "Защита от паразитов",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Защита от паразитов",
                            Slug = "anti-parasite-drops-cats",
                            StockQuantity = 73,
                            Title = "Антипаразитарные капли для кошек",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6186)
                        },
                        new
                        {
                            Id = new Guid("6084749d-cc5a-4f5e-b83e-553b383c2091"),
                            Brand = "BioGut",
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CountryOfOrigin = "Германия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6196),
                            Description = "Пробиотический комплекс для ЖКТ.",
                            ForWhom = "Собаки/Кошки",
                            IsAvailable = false,
                            Material = "Порошок",
                            OldPrice = 1390m,
                            PetSize = "Все размеры",
                            Price = 1190m,
                            Purpose = "Нормализация пищеварения",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Нормализация микрофлоры",
                            Slug = "probiotics-pet",
                            StockQuantity = 29,
                            Title = "Пробиотики для пищеварения",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6196)
                        },
                        new
                        {
                            Id = new Guid("ee3b9279-da4b-421e-ac3e-b5b7ae287463"),
                            Brand = "BoneGrow",
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CountryOfOrigin = "Россия",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6200),
                            Description = "Добавка для правильного формирования скелета.",
                            ForWhom = "Щенки",
                            IsAvailable = true,
                            Material = "Таблетки",
                            PetSize = "Маленький/Средний",
                            Price = 690m,
                            Purpose = "Рост костей и зубов",
                            Rating = 0m,
                            ReviewsCount = 0,
                            ShortDescription = "Кальций для роста костей",
                            Slug = "calcium-vitamin-d",
                            StockQuantity = 95,
                            Title = "Кальций с витамином D для щенков",
                            UpdatedAt = new DateTime(2026, 5, 10, 10, 29, 46, 321, DateTimeKind.Utc).AddTicks(6200)
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("888a71ca-89a2-46db-95e4-eb673e0423b3"),
                            Alt = "Royal Canin Adult Dog Food",
                            ProductId = new Guid("1b3647bc-92bd-483f-9aa4-d20130a619a9"),
                            Url = "https://picsum.photos/id/237/800/800"
                        },
                        new
                        {
                            Id = new Guid("b7251671-9507-427e-bf18-48d7f1b746e8"),
                            Alt = "Whiskas Wet Cat Food",
                            ProductId = new Guid("81acec04-ac74-4f06-861a-261b64eaae85"),
                            Url = "https://picsum.photos/id/1015/800/800"
                        },
                        new
                        {
                            Id = new Guid("ead41549-3889-4046-8bc4-64ea875b921a"),
                            Alt = "Pedigree Puppy Food",
                            ProductId = new Guid("a9ebd856-d30c-4f8b-8ed2-3ec918a0f865"),
                            Url = "https://picsum.photos/id/106/800/800"
                        },
                        new
                        {
                            Id = new Guid("30ec262f-fdb5-43b7-a33a-97154b8c4375"),
                            Alt = "Brit Care Grain-Free Salmon",
                            ProductId = new Guid("d7a9090a-6d01-4a36-9e9d-2fd9fef935a4"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("87cbe0c4-7ec2-46f5-9cf4-82935cf750b6"),
                            Alt = "Bosch Dog Treats",
                            ProductId = new Guid("f2539156-ab5d-4f0a-b542-dc9cc37c3239"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("75ae3540-0c66-4a2e-9522-a10973f19822"),
                            Alt = "Interactive Dog Ball",
                            ProductId = new Guid("3461d3bf-6549-4049-beb0-4651ab3a4f62"),
                            Url = "https://picsum.photos/id/180/800/800"
                        },
                        new
                        {
                            Id = new Guid("7ea300ee-8133-4df3-b553-6fe83d4c6c08"),
                            Alt = "Cat Feather Wand Toy",
                            ProductId = new Guid("c7b91735-1896-4dae-8b03-cfe3b90813f0"),
                            Url = "https://picsum.photos/id/133/800/800"
                        },
                        new
                        {
                            Id = new Guid("0acef4f6-1f49-4c9b-b060-a1dfcd8d1a6b"),
                            Alt = "Squeaky Plush Bear",
                            ProductId = new Guid("cbc1ac00-2283-45d3-b33e-0a7f1373ae2c"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("507f9145-f9e9-423e-8040-1ba9425b81c9"),
                            Alt = "Cat Laser Pointer",
                            ProductId = new Guid("9dac461d-d71a-4420-967f-dc397994f358"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("96fe18f1-4fd5-4072-b32a-e229cefc65fe"),
                            Alt = "Rope Tug Toy",
                            ProductId = new Guid("538fe373-3572-4dd1-b068-f923543f77d9"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("638775b9-c756-40e6-a9a4-5f194ea2f9c1"),
                            Alt = "Adjustable Dog Harness",
                            ProductId = new Guid("a3746572-16ff-4cf3-af67-0b8673bffcf7"),
                            Url = "https://picsum.photos/id/180/800/800"
                        },
                        new
                        {
                            Id = new Guid("7acf1837-b16d-4bfe-bf7d-22beddd798a9"),
                            Alt = "XL Dog Leash",
                            ProductId = new Guid("37083c6d-2711-44de-90a0-b0bf2684dcba"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("e3463a51-de06-4387-90d4-14d334fff245"),
                            Alt = "Warm Dog Jumpsuit",
                            ProductId = new Guid("3080a42d-ab57-414e-8925-82775c1de349"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("6c02e20a-62ac-4eba-8f95-edd7e158e583"),
                            Alt = "Ceramic Non-Slip Bowl",
                            ProductId = new Guid("ea88eab3-06a9-4614-80f9-dd8d457a498d"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("23749e10-3ffb-47e7-9f05-acab4ccb1220"),
                            Alt = "GPS Pet Collar",
                            ProductId = new Guid("23746c5a-0e90-4e6a-b902-445f92756b98"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("8014ec72-2be3-48b7-90ee-6e7b2a7e83a1"),
                            Alt = "Dog Shampoo",
                            ProductId = new Guid("ba872d50-5c81-40d4-954e-0ecdb0916efb"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("7d878183-83f1-46a6-af55-8bdcaa742dfa"),
                            Alt = "Pet Nail Clipper",
                            ProductId = new Guid("6b729cb8-c2dd-4ccf-89b3-05eed1d16c9b"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("874fa1ac-7b33-42b1-a26e-39d8328aa2f2"),
                            Alt = "Self-Cleaning Cat Brush",
                            ProductId = new Guid("3be4a5fa-fd45-453d-bbf9-1f314b747ff2"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("e56ba742-fdb3-4425-9a08-b85dde303b78"),
                            Alt = "Dry Dog Shampoo",
                            ProductId = new Guid("6d861eaf-a99e-4342-bbe2-c1529376bf06"),
                            Url = "https://picsum.photos/id/180/800/800"
                        },
                        new
                        {
                            Id = new Guid("ab8db22f-cc4a-4dd8-ad19-43ee6acc3d90"),
                            Alt = "Pet Dental Kit",
                            ProductId = new Guid("60a0315b-ebe9-46e4-b56e-acae29a356b6"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("4af4c958-11f2-4a3a-b207-6e142d3b4ed4"),
                            Alt = "Joint Supplement",
                            ProductId = new Guid("065f9a01-157f-4c29-9743-c9b1a562562d"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("edc88440-fe02-4232-bee6-17e8cd17013c"),
                            Alt = "Anti-Parasite Drops",
                            ProductId = new Guid("73db2a59-d927-4060-ab4a-a71a4ebd7f80"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("8c00c78e-56d3-44fe-a267-378159ffe89c"),
                            Alt = "Probiotics",
                            ProductId = new Guid("6084749d-cc5a-4f5e-b83e-553b383c2091"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("94c256b0-bf91-48e3-9002-1bcaa776667b"),
                            Alt = "Calcium with Vitamin D",
                            ProductId = new Guid("ee3b9279-da4b-421e-ac3e-b5b7ae287463"),
                            Url = "https://picsum.photos/id/180/800/800"
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReplyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "OrderId", "ProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ProductReviewImages");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewReplyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .IsUnique();

                    b.ToTable("ProductReviewReplys");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.User.FavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ProductId")
                        .IsUnique();

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartItemEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Cart.CartEntity", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderAddressEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Order.OrderEntity", "Order")
                        .WithOne("Address")
                        .HasForeignKey("Tailly.ShopService.Core.Entities.Order.OrderAddressEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Pickup.PickupPointEntity", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.Navigation("PickupPoint");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderItemEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Order.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductImageEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductEntity", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductEntity", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewImageEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewReplyEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", "Review")
                        .WithOne("Reply")
                        .HasForeignKey("Tailly.ShopService.Core.Entities.Product.ProductReviewReplyEntity", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderEntity", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductEntity", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reply");
                });
#pragma warning restore 612, 618
        }
    }
}
