// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailly.ShopService.Infrastructure.DataAccess;

#nullable disable

namespace Tailly.ShopService.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"SessionId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderAddresses");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanBeCancelled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PickupPointId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecipientFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PickupPointId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductSlug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Pickup.PickupPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EstimatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PickupPoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5802f5a-ad2d-4a07-8973-febfb61c323d"),
                            Address = "Москва, ул. Тверская, 12, стр. 1",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3470),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Тверской"
                        },
                        new
                        {
                            Id = new Guid("1160b6c1-94f8-4bce-acd0-983984127815"),
                            Address = "Москва, ул. Братиславская, 21, корп. 2",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3472),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Марьино"
                        },
                        new
                        {
                            Id = new Guid("ac0d7301-e88e-4db4-88e4-df62f317fd53"),
                            Address = "Москва, Ленинский проспект, 45",
                            EstimatedDate = new DateTime(2026, 4, 13, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3474),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Ленинском проспекте"
                        },
                        new
                        {
                            Id = new Guid("18133511-4538-415e-b759-4f06cf5c1d39"),
                            Address = "Москва, г. Химки, ул. Ленинградская, 29",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3475),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Химках"
                        },
                        new
                        {
                            Id = new Guid("a2dd8080-ecac-4f57-adf5-2f6c67dd1f3a"),
                            Address = "Москва, проспект Мира, 119, стр. 23",
                            EstimatedDate = new DateTime(2026, 4, 13, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3477),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на ВДНХ"
                        },
                        new
                        {
                            Id = new Guid("f63b286f-dc06-4f74-b7ef-01c3e3598b03"),
                            Address = "Санкт-Петербург, Невский проспект, 56",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3481),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Невском"
                        },
                        new
                        {
                            Id = new Guid("86390af9-c7bd-428b-a506-a3d8f2584688"),
                            Address = "Санкт-Петербург, ул. Будапештская, 18",
                            EstimatedDate = new DateTime(2026, 4, 13, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3483),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Купчино"
                        },
                        new
                        {
                            Id = new Guid("8260749b-f7c1-4949-8274-7b2cd9585024"),
                            Address = "Санкт-Петербург, Московский проспект, 183",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3485),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Московском проспекте"
                        },
                        new
                        {
                            Id = new Guid("d0f1984e-d1cb-4501-9029-c35bba68aeb7"),
                            Address = "Санкт-Петербург, пр. Испытателей, 15",
                            EstimatedDate = new DateTime(2026, 4, 13, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3486),
                            Provider = 1,
                            Title = "ПВЗ СДЭК у станции метро Пионерская"
                        },
                        new
                        {
                            Id = new Guid("027286f6-ee4d-4c0c-9e7a-cbd0af7ea442"),
                            Address = "Екатеринбург, ул. Малышева, 51",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3488),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Малышева"
                        },
                        new
                        {
                            Id = new Guid("258dcde6-c023-4b42-b10a-fd405ae55671"),
                            Address = "Екатеринбург, ул. Космонавтов, 11/1",
                            EstimatedDate = new DateTime(2026, 4, 13, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3489),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Уралмаше"
                        },
                        new
                        {
                            Id = new Guid("f4665b4f-ef7d-46a4-8fd5-dbfe7a137c32"),
                            Address = "Новосибирск, Красный проспект, 52",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3491),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Красном проспекте"
                        },
                        new
                        {
                            Id = new Guid("1205a018-3ac4-458f-b1ad-96747a0cba5c"),
                            Address = "Новосибирск, ул. Ильича, 10",
                            EstimatedDate = new DateTime(2026, 4, 14, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3493),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Академгородке"
                        },
                        new
                        {
                            Id = new Guid("c85f7634-b297-412d-ba59-e55eeab519c0"),
                            Address = "Казань, ул. Баумана, 27",
                            EstimatedDate = new DateTime(2026, 4, 12, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3496),
                            Provider = 1,
                            Title = "ПВЗ СДЭК на Баумана"
                        },
                        new
                        {
                            Id = new Guid("fd250fe9-51d1-4971-8769-cb38d81165ea"),
                            Address = "Казань, пр. Победы, 74",
                            EstimatedDate = new DateTime(2026, 4, 13, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3498),
                            Provider = 1,
                            Title = "ПВЗ СДЭК в Советском районе"
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Slug = "food",
                            Title = "Корм и лакомства"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Slug = "toys",
                            Title = "Игрушки и развлечения"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Slug = "accessories",
                            Title = "Аксессуары и одежда"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Slug = "grooming",
                            Title = "Груминг и уход"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Slug = "health",
                            Title = "Здоровье и витамины"
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Price");

                    b.HasIndex("Rating");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b3647bc-92bd-483f-9aa4-d20130a619a9"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3127),
                            Description = "Премиальный полнорационный корм для собак старше 1 года. Поддерживает иммунитет и здоровье пищеварения.",
                            IsAvailable = true,
                            OldPrice = 2790m,
                            Price = 2490m,
                            Rating = 4.9m,
                            ReviewsCount = 234,
                            ShortDescription = "Сухой корм для взрослых собак",
                            Slug = "royal-canin-adult-dog",
                            StockQuantity = 87,
                            Title = "Royal Canin Adult Dog Food",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3128)
                        },
                        new
                        {
                            Id = new Guid("81acec04-ac74-4f06-861a-261b64eaae85"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3132),
                            Description = "Нежные кусочки в соусе. Идеальный рацион для взрослых кошек.",
                            IsAvailable = true,
                            Price = 89m,
                            Rating = 4.7m,
                            ReviewsCount = 189,
                            ShortDescription = "Влажный корм для кошек",
                            Slug = "whiskas-wet-chicken",
                            StockQuantity = 320,
                            Title = "Whiskas Wet Cat Food с курицей",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3132)
                        },
                        new
                        {
                            Id = new Guid("a9ebd856-d30c-4f8b-8ed2-3ec918a0f865"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3136),
                            Description = "Сбалансированное питание для правильного роста и развития щенков.",
                            IsAvailable = true,
                            OldPrice = 2190m,
                            Price = 1890m,
                            Rating = 4.8m,
                            ReviewsCount = 98,
                            ShortDescription = "Корм для щенков всех пород",
                            Slug = "pedigree-puppy",
                            StockQuantity = 64,
                            Title = "Pedigree Puppy для щенков",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3137)
                        },
                        new
                        {
                            Id = new Guid("d7a9090a-6d01-4a36-9e9d-2fd9fef935a4"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3141),
                            Description = "Гипоаллергенный корм для собак с чувствительным пищеварением.",
                            IsAvailable = true,
                            Price = 3190m,
                            Rating = 4.9m,
                            ReviewsCount = 156,
                            ShortDescription = "Беззерновой корм с лососем",
                            Slug = "brit-care-salmon",
                            StockQuantity = 45,
                            Title = "Brit Care Grain-Free Salmon",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3141)
                        },
                        new
                        {
                            Id = new Guid("f2539156-ab5d-4f0a-b542-dc9cc37c3239"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3145),
                            Description = "Полезные косточки и палочки для поощрения.",
                            IsAvailable = true,
                            OldPrice = 590m,
                            Price = 450m,
                            Rating = 4.6m,
                            ReviewsCount = 87,
                            ShortDescription = "Натуральные лакомства",
                            Slug = "bosch-dog-treats",
                            StockQuantity = 210,
                            Title = "Лакомство для собак Bosch",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3145)
                        },
                        new
                        {
                            Id = new Guid("3461d3bf-6549-4049-beb0-4651ab3a4f62"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3149),
                            Description = "Автоматический мячик с несколькими режимами движения.",
                            IsAvailable = true,
                            OldPrice = 1590m,
                            Price = 1290m,
                            Rating = 4.6m,
                            ReviewsCount = 156,
                            ShortDescription = "Умная игрушка с движением",
                            Slug = "interactive-dog-ball",
                            StockQuantity = 42,
                            Title = "Интерактивный мяч для собак",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3150)
                        },
                        new
                        {
                            Id = new Guid("c7b91735-1896-4dae-8b03-cfe3b90813f0"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3153),
                            Description = "Лёгкая удочка с яркими перьями.",
                            IsAvailable = true,
                            Price = 490m,
                            Rating = 4.9m,
                            ReviewsCount = 312,
                            ShortDescription = "Любимая игрушка кошек",
                            Slug = "cat-feather-wand",
                            StockQuantity = 95,
                            Title = "Дразнилка с перьями для кошек",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3154)
                        },
                        new
                        {
                            Id = new Guid("cbc1ac00-2283-45d3-b33e-0a7f1373ae2c"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3162),
                            Description = "Прочный плюш с пищалкой внутри.",
                            IsAvailable = true,
                            OldPrice = 1190m,
                            Price = 890m,
                            Rating = 4.5m,
                            ReviewsCount = 134,
                            ShortDescription = "Мягкая пищащая игрушка",
                            Slug = "squeaky-plush-bear",
                            StockQuantity = 67,
                            Title = "Пищащий плюшевый медведь",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3162)
                        },
                        new
                        {
                            Id = new Guid("9dac461d-d71a-4420-967f-dc397994f358"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3165),
                            Description = "Классическая лазерная указка.",
                            IsAvailable = true,
                            Price = 390m,
                            Rating = 4.8m,
                            ReviewsCount = 245,
                            ShortDescription = "Лазер для активных игр",
                            Slug = "cat-laser-pointer",
                            StockQuantity = 180,
                            Title = "Лазерная указка для кошек",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3166)
                        },
                        new
                        {
                            Id = new Guid("538fe373-3572-4dd1-b068-f923543f77d9"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3169),
                            Description = "Прочный канат для игр с собакой.",
                            IsAvailable = true,
                            OldPrice = 890m,
                            Price = 690m,
                            Rating = 4.7m,
                            ReviewsCount = 98,
                            ShortDescription = "Крепкий канат",
                            Slug = "rope-tug-toy",
                            StockQuantity = 53,
                            Title = "Канатная игрушка для перетягивания",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3169)
                        },
                        new
                        {
                            Id = new Guid("a3746572-16ff-4cf3-af67-0b8673bffcf7"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3172),
                            Description = "Мягкая и удобная шлейка для средних и крупных собак.",
                            IsAvailable = true,
                            Price = 1690m,
                            Rating = 4.8m,
                            ReviewsCount = 112,
                            ShortDescription = "Комфортная шлейка",
                            Slug = "adjustable-dog-harness",
                            StockQuantity = 28,
                            Title = "Регулируемая шлейка для собак",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3172)
                        },
                        new
                        {
                            Id = new Guid("37083c6d-2711-44de-90a0-b0bf2684dcba"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3176),
                            Description = "Надёжный нейлоновый поводок для крупных собак.",
                            IsAvailable = true,
                            OldPrice = 1490m,
                            Price = 1290m,
                            Rating = 4.7m,
                            ReviewsCount = 87,
                            ShortDescription = "Прочный поводок",
                            Slug = "xl-nylon-leash",
                            StockQuantity = 33,
                            Title = "Поводок нейлоновый XL",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3176)
                        },
                        new
                        {
                            Id = new Guid("3080a42d-ab57-414e-8925-82775c1de349"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3179),
                            Description = "Утеплённый комбинезон с капюшоном.",
                            IsAvailable = true,
                            OldPrice = 2590m,
                            Price = 2190m,
                            Rating = 4.9m,
                            ReviewsCount = 76,
                            ShortDescription = "Зимняя одежда для собак",
                            Slug = "warm-dog-jumpsuit",
                            StockQuantity = 19,
                            Title = "Теплый комбинезон для собак",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3180)
                        },
                        new
                        {
                            Id = new Guid("ea88eab3-06a9-4614-80f9-dd8d457a498d"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3182),
                            Description = "Керамическая миска с резиновым основанием.",
                            IsAvailable = true,
                            Price = 790m,
                            Rating = 4.6m,
                            ReviewsCount = 203,
                            ShortDescription = "Устойчивая миска",
                            Slug = "ceramic-non-slip-bowl",
                            StockQuantity = 124,
                            Title = "Миска керамическая антискользящая",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3183)
                        },
                        new
                        {
                            Id = new Guid("23746c5a-0e90-4e6a-b902-445f92756b98"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3188),
                            Description = "Ошейник с GPS и отслеживанием активности.",
                            IsAvailable = true,
                            OldPrice = 3990m,
                            Price = 3490m,
                            Rating = 4.4m,
                            ReviewsCount = 45,
                            ShortDescription = "Умный ошейник",
                            Slug = "gps-pet-collar",
                            StockQuantity = 12,
                            Title = "Ошейник с GPS-трекером",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3188)
                        },
                        new
                        {
                            Id = new Guid("ba872d50-5c81-40d4-954e-0ecdb0916efb"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3191),
                            Description = "Натуральный шампунь с экстрактом алоэ.",
                            IsAvailable = true,
                            OldPrice = 990m,
                            Price = 790m,
                            Rating = 4.6m,
                            ReviewsCount = 95,
                            ShortDescription = "Гипоаллергенный шампунь",
                            Slug = "dog-shampoo-aloe",
                            StockQuantity = 47,
                            Title = "Шампунь для собак с алоэ",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3192)
                        },
                        new
                        {
                            Id = new Guid("6b729cb8-c2dd-4ccf-89b3-05eed1d16c9b"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3194),
                            Description = "Профессиональный когтерез с ограничителем.",
                            IsAvailable = true,
                            Price = 690m,
                            Rating = 4.4m,
                            ReviewsCount = 73,
                            ShortDescription = "Безопасный когтерез",
                            Slug = "pet-nail-clipper",
                            StockQuantity = 55,
                            Title = "Когтерез для животных",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3195)
                        },
                        new
                        {
                            Id = new Guid("3be4a5fa-fd45-453d-bbf9-1f314b747ff2"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3198),
                            Description = "Удобная щётка для удаления выпавшей шерсти.",
                            IsAvailable = true,
                            OldPrice = 790m,
                            Price = 590m,
                            Rating = 4.9m,
                            ReviewsCount = 128,
                            ShortDescription = "Щётка с самоочисткой",
                            Slug = "self-cleaning-cat-brush",
                            StockQuantity = 68,
                            Title = "Самоочищающаяся щетка для кошек",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3198)
                        },
                        new
                        {
                            Id = new Guid("6d861eaf-a99e-4342-bbe2-c1529376bf06"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3248),
                            Description = "Быстрое очищение шерсти без купания.",
                            IsAvailable = true,
                            Price = 890m,
                            Rating = 4.5m,
                            ReviewsCount = 64,
                            ShortDescription = "Сухой шампунь без воды",
                            Slug = "dry-dog-shampoo",
                            StockQuantity = 82,
                            Title = "Сухой шампунь для собак",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3249)
                        },
                        new
                        {
                            Id = new Guid("60a0315b-ebe9-46e4-b56e-acae29a356b6"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3252),
                            Description = "Полный набор для ухода за зубами.",
                            IsAvailable = true,
                            OldPrice = 1490m,
                            Price = 1290m,
                            Rating = 4.8m,
                            ReviewsCount = 109,
                            ShortDescription = "Гигиена полости рта",
                            Slug = "pet-dental-kit",
                            StockQuantity = 37,
                            Title = "Набор для чистки зубов питомцам",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3252)
                        },
                        new
                        {
                            Id = new Guid("065f9a01-157f-4c29-9743-c9b1a562562d"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3256),
                            Description = "Комплекс для укрепления суставов и хрящей.",
                            IsAvailable = true,
                            OldPrice = 1790m,
                            Price = 1490m,
                            Rating = 4.7m,
                            ReviewsCount = 142,
                            ShortDescription = "Поддержка суставов",
                            Slug = "joint-supplement-dogs",
                            StockQuantity = 51,
                            Title = "Витамины для суставов собак",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3257)
                        },
                        new
                        {
                            Id = new Guid("73db2a59-d927-4060-ab4a-a71a4ebd7f80"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3260),
                            Description = "Капли на холку от блох и клещей.",
                            IsAvailable = true,
                            Price = 890m,
                            Rating = 4.9m,
                            ReviewsCount = 201,
                            ShortDescription = "Защита от паразитов",
                            Slug = "anti-parasite-drops-cats",
                            StockQuantity = 73,
                            Title = "Антипаразитарные капли для кошек",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3260)
                        },
                        new
                        {
                            Id = new Guid("6084749d-cc5a-4f5e-b83e-553b383c2091"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3266),
                            Description = "Пробиотический комплекс для ЖКТ.",
                            IsAvailable = true,
                            OldPrice = 1390m,
                            Price = 1190m,
                            Rating = 4.6m,
                            ReviewsCount = 88,
                            ShortDescription = "Нормализация микрофлоры",
                            Slug = "probiotics-pet",
                            StockQuantity = 29,
                            Title = "Пробиотики для пищеварения",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3266)
                        },
                        new
                        {
                            Id = new Guid("ee3b9279-da4b-421e-ac3e-b5b7ae287463"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3270),
                            Description = "Добавка для правильного формирования скелета.",
                            IsAvailable = true,
                            Price = 690m,
                            Rating = 4.8m,
                            ReviewsCount = 67,
                            ShortDescription = "Кальций для роста костей",
                            Slug = "calcium-vitamin-d",
                            StockQuantity = 95,
                            Title = "Кальций с витамином D для щенков",
                            UpdatedAt = new DateTime(2026, 4, 11, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3270)
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0622040-7e6c-4cd1-9bed-9f6fe84c202f"),
                            Alt = "Royal Canin Adult Dog Food",
                            ProductId = new Guid("1b3647bc-92bd-483f-9aa4-d20130a619a9"),
                            Url = "https://picsum.photos/id/237/800/800"
                        },
                        new
                        {
                            Id = new Guid("c3d397c9-1446-425c-94b9-1e338f79ca7b"),
                            Alt = "Whiskas Wet Cat Food",
                            ProductId = new Guid("81acec04-ac74-4f06-861a-261b64eaae85"),
                            Url = "https://picsum.photos/id/1015/800/800"
                        },
                        new
                        {
                            Id = new Guid("08a8fa90-bce7-4ed9-9f34-9eff534817f6"),
                            Alt = "Pedigree Puppy Food",
                            ProductId = new Guid("a9ebd856-d30c-4f8b-8ed2-3ec918a0f865"),
                            Url = "https://picsum.photos/id/106/800/800"
                        },
                        new
                        {
                            Id = new Guid("63fd849b-949b-46a0-bad3-21e0576f42aa"),
                            Alt = "Brit Care Grain-Free Salmon",
                            ProductId = new Guid("d7a9090a-6d01-4a36-9e9d-2fd9fef935a4"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("b1648ab6-3b33-4ee8-aea9-c5801c390362"),
                            Alt = "Bosch Dog Treats",
                            ProductId = new Guid("f2539156-ab5d-4f0a-b542-dc9cc37c3239"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("75b584f9-f586-4471-aaed-63cbaef9431f"),
                            Alt = "Interactive Dog Ball",
                            ProductId = new Guid("3461d3bf-6549-4049-beb0-4651ab3a4f62"),
                            Url = "https://picsum.photos/id/180/800/800"
                        },
                        new
                        {
                            Id = new Guid("7069ec83-43e8-471f-b72e-847b8165c3f4"),
                            Alt = "Cat Feather Wand Toy",
                            ProductId = new Guid("c7b91735-1896-4dae-8b03-cfe3b90813f0"),
                            Url = "https://picsum.photos/id/133/800/800"
                        },
                        new
                        {
                            Id = new Guid("d2c838f6-f2d7-4069-a59a-d730c970e04a"),
                            Alt = "Squeaky Plush Bear",
                            ProductId = new Guid("cbc1ac00-2283-45d3-b33e-0a7f1373ae2c"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("147eed91-5c88-4b4e-af56-bbb388d70840"),
                            Alt = "Cat Laser Pointer",
                            ProductId = new Guid("9dac461d-d71a-4420-967f-dc397994f358"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("a34a10e8-e3cf-4699-86fe-12d293f03c64"),
                            Alt = "Rope Tug Toy",
                            ProductId = new Guid("538fe373-3572-4dd1-b068-f923543f77d9"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("0c527aec-7be0-4c8a-ac6c-4eef7a041ecb"),
                            Alt = "Adjustable Dog Harness",
                            ProductId = new Guid("a3746572-16ff-4cf3-af67-0b8673bffcf7"),
                            Url = "https://picsum.photos/id/180/800/800"
                        },
                        new
                        {
                            Id = new Guid("0a27abb0-6860-4da7-a1aa-8437b6d9a635"),
                            Alt = "XL Dog Leash",
                            ProductId = new Guid("37083c6d-2711-44de-90a0-b0bf2684dcba"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("80aa83de-c471-451d-8573-38cc96512807"),
                            Alt = "Warm Dog Jumpsuit",
                            ProductId = new Guid("3080a42d-ab57-414e-8925-82775c1de349"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("061053b7-f878-4dbb-afca-d305e9abc210"),
                            Alt = "Ceramic Non-Slip Bowl",
                            ProductId = new Guid("ea88eab3-06a9-4614-80f9-dd8d457a498d"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("91f5fda3-385e-482e-95ea-88fdff77a417"),
                            Alt = "GPS Pet Collar",
                            ProductId = new Guid("23746c5a-0e90-4e6a-b902-445f92756b98"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("870e4897-a009-473b-b61d-a2ce2960adda"),
                            Alt = "Dog Shampoo",
                            ProductId = new Guid("ba872d50-5c81-40d4-954e-0ecdb0916efb"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("6b9d0e93-82fe-48ce-a3c5-a59075e4f502"),
                            Alt = "Pet Nail Clipper",
                            ProductId = new Guid("6b729cb8-c2dd-4ccf-89b3-05eed1d16c9b"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("cf8c1216-2660-4966-a673-5feba3690e15"),
                            Alt = "Self-Cleaning Cat Brush",
                            ProductId = new Guid("3be4a5fa-fd45-453d-bbf9-1f314b747ff2"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("7ebc623a-0a71-42ed-8690-82b612185aa5"),
                            Alt = "Dry Dog Shampoo",
                            ProductId = new Guid("6d861eaf-a99e-4342-bbe2-c1529376bf06"),
                            Url = "https://picsum.photos/id/180/800/800"
                        },
                        new
                        {
                            Id = new Guid("2a7ddade-bed3-4607-abd8-f89a1228cfed"),
                            Alt = "Pet Dental Kit",
                            ProductId = new Guid("60a0315b-ebe9-46e4-b56e-acae29a356b6"),
                            Url = "https://picsum.photos/id/201/800/800"
                        },
                        new
                        {
                            Id = new Guid("62c99431-90e1-4189-ba92-8f61d7e2c074"),
                            Alt = "Joint Supplement",
                            ProductId = new Guid("065f9a01-157f-4c29-9743-c9b1a562562d"),
                            Url = "https://picsum.photos/id/251/800/800"
                        },
                        new
                        {
                            Id = new Guid("1cf2ce5f-1044-4193-89d1-7e3560714d5c"),
                            Alt = "Anti-Parasite Drops",
                            ProductId = new Guid("73db2a59-d927-4060-ab4a-a71a4ebd7f80"),
                            Url = "https://picsum.photos/id/367/800/800"
                        },
                        new
                        {
                            Id = new Guid("58d65ca7-1edc-4caa-8b4a-a9e41ea0881a"),
                            Alt = "Probiotics",
                            ProductId = new Guid("6084749d-cc5a-4f5e-b83e-553b383c2091"),
                            Url = "https://picsum.photos/id/433/800/800"
                        },
                        new
                        {
                            Id = new Guid("43443ae0-e95b-43aa-a452-0d7dfaf728a0"),
                            Alt = "Calcium with Vitamin D",
                            ProductId = new Guid("ee3b9279-da4b-421e-ac3e-b5b7ae287463"),
                            Url = "https://picsum.photos/id/180/800/800"
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AuthorName = "Анна Смирнова",
                            CreatedAt = new DateTime(2026, 2, 25, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3422),
                            ProductId = new Guid("1b3647bc-92bd-483f-9aa4-d20130a619a9"),
                            Rating = 5,
                            Text = "Отличный корм! Собака ест с огромным удовольствием, шерсть стала намного лучше."
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            AuthorName = "Дмитрий Волков",
                            CreatedAt = new DateTime(2026, 3, 22, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3427),
                            ProductId = new Guid("3461d3bf-6549-4049-beb0-4651ab3a4f62"),
                            Rating = 5,
                            Text = "Лучшая игрушка за последнее время! Собака не может остановиться."
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewReplyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .IsUnique();

                    b.ToTable("ProductReviewReplys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5873dcb6-0a40-4028-8430-8b2a0e9dbc80"),
                            AuthorName = "Tailly Shop",
                            CreatedAt = new DateTime(2026, 2, 26, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3446),
                            ReviewId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Спасибо большое за отзыв, Анна! Очень рады, что вашему питомцу нравится наш корм ❤️"
                        },
                        new
                        {
                            Id = new Guid("dbd50f66-98e0-4354-857d-07b9badb1cab"),
                            AuthorName = "Tailly Shop",
                            CreatedAt = new DateTime(2026, 3, 23, 10, 10, 55, 494, DateTimeKind.Utc).AddTicks(3448),
                            ReviewId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Text = "Рады, что игрушка понравилась! Это один из наших бестселлеров."
                        });
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.User.FavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ProductId")
                        .IsUnique();

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartItemEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Cart.CartEntity", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderAddressEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Order.OrderEntity", "Order")
                        .WithOne("Address")
                        .HasForeignKey("Tailly.ShopService.Core.Entities.Order.OrderAddressEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Pickup.PickupPointEntity", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.Navigation("PickupPoint");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderItemEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Order.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductImageEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductEntity", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductEntity", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewReplyEntity", b =>
                {
                    b.HasOne("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", "Review")
                        .WithOne("Reply")
                        .HasForeignKey("Tailly.ShopService.Core.Entities.Product.ProductReviewReplyEntity", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Cart.CartEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Order.OrderEntity", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductEntity", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Tailly.ShopService.Core.Entities.Product.ProductReviewEntity", b =>
                {
                    b.Navigation("Reply");
                });
#pragma warning restore 612, 618
        }
    }
}
