// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailly.ClientProfileService.Infrastructure.DataAccess;

#nullable disable

namespace Tailly.ClientProfileService.Migrations
{
    [DbContext(typeof(ClientProfileDbContext))]
    [Migration("20260510114110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.BreedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Title");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be045962-4d3a-4cf5-8414-12613419bb2a"),
                            Title = "Лабрадор",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("75a77134-6b6f-40e1-a642-a3a4cd0b2fce"),
                            Title = "Немецкая овчарка",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("37990fe4-6b76-475f-a378-98eea7acbc26"),
                            Title = "Французский бульдог",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0532630b-bbe8-4a9c-93ec-9665e3c583d7"),
                            Title = "Корги",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1c2e950c-6164-465b-b0ec-0259594c34ae"),
                            Title = "Хаски",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d4302ee8-7b5d-4a29-a572-f3587404e6e4"),
                            Title = "Мейн-кун",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("80596eed-28f8-4961-8fd5-9d0eba0bd06c"),
                            Title = "Шотландская вислоухая",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("0afc029f-2bac-4b5a-9663-054c089658c6"),
                            Title = "Сиамская",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("4dd3be4e-dc09-45bd-b12e-1ed59fbd90bd"),
                            Title = "Британская короткошерстная",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7c19145a-7818-4beb-8800-f3cff753eb60"),
                            Title = "Рэгдолл",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d44c9777-1298-4cae-9d72-2fcf80af9c19"),
                            Title = "Волнистый попугай",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("a3815616-d7df-4403-be61-455e9728b2bf"),
                            Title = "Корелла",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("110d4844-2c68-4b28-afcc-e198a6e384b3"),
                            Title = "Лев",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("9a0fdece-deb0-43b7-81ef-0d6adb6c82ef"),
                            Title = "Баран",
                            Type = 5
                        });
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.ClientProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CityId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.PetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("integer");

                    b.Property<int>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BreedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int?>("StaysHomeAlone")
                        .HasColumnType("integer");

                    b.Property<int?>("ToKidsUnder10")
                        .HasColumnType("integer");

                    b.Property<int?>("ToOtherPets")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Vaccinated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("ClientId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.PetEntity", b =>
                {
                    b.HasOne("Tailly.ClientProfileService.Core.Entities.BreedEntity", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tailly.ClientProfileService.Core.Entities.ClientProfileEntity", "ClientProfile")
                        .WithMany("Pets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.ClientProfileEntity", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
