// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailly.ClientProfileService.Infrastructure.DataAccess;

#nullable disable

namespace Tailly.ClientProfileService.Migrations
{
    [DbContext(typeof(ClientProfileDbContext))]
    partial class ClientProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.BreedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Title");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf34adf6-b6b8-4d7b-8ad7-059e61779959"),
                            Title = "Лабрадор",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a6ec99c7-be94-4046-8531-d8e6578faaf9"),
                            Title = "Немецкая овчарка",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d769028b-25cb-4fce-b62e-f56f9522181a"),
                            Title = "Французский бульдог",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("78df31ee-dec8-4ef1-af30-78f256c5a09b"),
                            Title = "Корги",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7d17f57c-2fce-4038-9932-e5a0e799203b"),
                            Title = "Хаски",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("93faa429-0ad0-404d-b023-09a72a797d6b"),
                            Title = "Мейн-кун",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("3d604913-3ade-44aa-bb3f-3b7660a84ade"),
                            Title = "Шотландская вислоухая",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f70bbcf4-5791-4d6f-9121-5732c2ca31b1"),
                            Title = "Сиамская",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f660d9e9-5450-43b5-a86a-dbb07d51d113"),
                            Title = "Британская короткошерстная",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("157aa2cd-7cca-4653-acf5-30d2d3b31019"),
                            Title = "Рэгдолл",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("2b415f4b-9698-45e5-b582-d67c9e7e88cf"),
                            Title = "Волнистый попугай",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("1e05f6b1-a905-4b97-9aec-858904573f36"),
                            Title = "Корелла",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("06febfb9-8c1e-473f-a4f8-9180fcd9f7bb"),
                            Title = "Лев",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("2d47440e-69ff-4364-b5ba-9ecd604255b9"),
                            Title = "Баран",
                            Type = 5
                        });
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.ClientProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CityId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.PetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("integer");

                    b.Property<int>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BreedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int?>("StaysHomeAlone")
                        .HasColumnType("integer");

                    b.Property<int?>("ToKidsUnder10")
                        .HasColumnType("integer");

                    b.Property<int?>("ToOtherPets")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Vaccinated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("ClientId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.PetEntity", b =>
                {
                    b.HasOne("Tailly.ClientProfileService.Core.Entities.BreedEntity", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tailly.ClientProfileService.Core.Entities.ClientProfileEntity", "ClientProfile")
                        .WithMany("Pets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("Tailly.ClientProfileService.Core.Entities.ClientProfileEntity", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
