// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailly.SpecialistService.Infrastructure.DataAccess;

#nullable disable

namespace Tailly.SpecialistService.Migrations
{
    [DbContext(typeof(SpecialistDbContext))]
    [Migration("20260508140457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Applications.SpecialistApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AnimalTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("CanGiveMedication")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanHandleDifficultBehavior")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTakeOvernightOrders")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedSpecialistId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedSpecialistSlug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DistrictPreferences")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ExperienceYears")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasOwnPets")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPetFirstAidBasics")
                        .HasColumnType("boolean");

                    b.Property<string>("HousingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InterviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SchedulePreferences")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ServiceFormats")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("SpecialistAccountCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("SpecialistApplications");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarAvailabilityWindowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId", "Date");

                    b.ToTable("CalendarAvailabilityWindows");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarBookedSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId", "Date");

                    b.ToTable("CalendarBookedSlots");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarBookingSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<string>("DayEndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DayStartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SlotStepMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId")
                        .IsUnique();

                    b.ToTable("CalendarBookingSettings");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarDayOverrideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId", "Date");

                    b.ToTable("CalendarDayOverrides");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId")
                        .IsUnique();

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6e0fea6-4b86-4001-be26-29800be5c900"),
                            SpecialistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Timezone = "Europe/Moscow"
                        },
                        new
                        {
                            Id = new Guid("c2a498d2-75f5-4846-ad8b-87106e566de4"),
                            SpecialistId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Timezone = "Europe/Moscow"
                        },
                        new
                        {
                            Id = new Guid("44733e3a-29f9-4371-a4be-14d6a5e02b16"),
                            SpecialistId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Timezone = "Europe/Moscow"
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("HasChildrenUnderTen")
                        .HasColumnType("integer");

                    b.Property<int>("HousingType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId")
                        .IsUnique();

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            About = "Люблю животных, имею двух своих собак. Занимаюсь выгулом и передержкой уже более 5 лет.",
                            HasChildrenUnderTen = 2,
                            HousingType = 1,
                            SpecialistId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            About = "Профессиональный выгульщик с опытом работы с крупными породами.",
                            HasChildrenUnderTen = 1,
                            HousingType = 2,
                            SpecialistId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            About = "Профессиональный грумер собак и кошек с 7-летним стажем.",
                            HasChildrenUnderTen = 3,
                            HousingType = 1,
                            SpecialistId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.PetAgeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailsId")
                        .HasColumnType("uuid");

                    b.Property<int>("PetAge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("PetAges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24cf62f2-ecec-4b3f-b806-38ba28b6fc78"),
                            DetailsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PetAge = 3
                        },
                        new
                        {
                            Id = new Guid("5934c383-839d-4a8c-8392-feefd2e1ab57"),
                            DetailsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PetAge = 4
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.PetSizeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailsId")
                        .HasColumnType("uuid");

                    b.Property<int>("PetSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("PetSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89833d44-ea5f-423d-b19b-9c2e1eb9783b"),
                            DetailsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PetSize = 2
                        },
                        new
                        {
                            Id = new Guid("7abf6d66-d2db-4e2f-b9d8-023e0246da5a"),
                            DetailsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PetSize = 3
                        },
                        new
                        {
                            Id = new Guid("4b4854ad-b0b6-4e72-9439-f5f601f7b9b8"),
                            DetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PetSize = 4
                        },
                        new
                        {
                            Id = new Guid("d3d93b21-7e7e-45e3-a5f1-15e5f707dffd"),
                            DetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PetSize = 5
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.PetTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailsId")
                        .HasColumnType("uuid");

                    b.Property<int>("PetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11150932-055f-4f0d-97e8-12c88e1179e6"),
                            DetailsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PetType = 1
                        },
                        new
                        {
                            Id = new Guid("ac496664-f005-4d33-ae0e-d05bf2adf112"),
                            DetailsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PetType = 2
                        },
                        new
                        {
                            Id = new Guid("3aa32ec3-f085-4337-a9fe-409e34b63245"),
                            DetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PetType = 1
                        },
                        new
                        {
                            Id = new Guid("65b9f374-92bc-4d00-9b77-0ba77916ff91"),
                            DetailsId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            PetType = 1
                        },
                        new
                        {
                            Id = new Guid("f2cc3f03-70f2-4524-b7a3-62f29eb1dcf7"),
                            DetailsId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            PetType = 2
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Gallery.SpecialistGalleryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId", "Order");

                    b.ToTable("SpecialistGalleries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c797f51-5100-4a92-9b5b-67ec2498dc94"),
                            Alt = "Анна с питомцем",
                            ImageUrl = "/uploads/gallery/anna1.jpg",
                            Order = 1,
                            SpecialistId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("0e28d891-7e5c-4caa-ad41-d5a44c24df29"),
                            Alt = "Анна на прогулке",
                            ImageUrl = "/uploads/gallery/anna2.jpg",
                            Order = 2,
                            SpecialistId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Reviews.ReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PetName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("Photos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReplyCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplyText")
                        .HasColumnType("text");

                    b.Property<string>("ServiceTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Services.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PriceUnit")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18803d15-7feb-4ba8-9ec3-7b65418d8de7"),
                            Description = "Выгул собаки 60 минут",
                            Name = 1,
                            Price = 1200m,
                            PriceUnit = 4,
                            SpecialistId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("2d9bcfc7-897e-4b89-a3ea-67fb58d146f4"),
                            Description = "Комфортная передержка в квартире",
                            Name = 2,
                            Price = 2500m,
                            PriceUnit = 2,
                            SpecialistId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("a0a85b66-ac0f-4604-8727-e6dc052cd174"),
                            Description = "Выгул с элементами дрессировки",
                            Name = 5,
                            Price = 1800m,
                            PriceUnit = 1,
                            SpecialistId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("fe894bf6-3eb7-4341-b34d-d341e20d2128"),
                            Description = "Полный груминг",
                            Name = 3,
                            Price = 3500m,
                            PriceUnit = 3,
                            SpecialistId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("CompletedOrdersCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<int>("RepeatOrdersCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvatarUrl = "/uploads/avatars/anna.jpg",
                            City = "Москва",
                            CompletedOrdersCount = 87,
                            CreatedAt = new DateTime(2025, 11, 8, 14, 4, 56, 434, DateTimeKind.Utc).AddTicks(5976),
                            District = "Сокольники",
                            Email = "anna@example.com",
                            ExperienceYears = 5,
                            FirstName = "Анна",
                            LastName = "Смирнова",
                            Latitude = 55.793100000000003,
                            Longitude = 37.677799999999998,
                            Phone = "+79161234567",
                            Rating = 4.8m,
                            RepeatOrdersCount = 24,
                            ReviewsCount = 42,
                            Slug = "anna-petcare",
                            UserId = new Guid("438a4a9e-c17b-439d-ab8b-007ed01d2ac8")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            City = "Москва",
                            CompletedOrdersCount = 45,
                            CreatedAt = new DateTime(2026, 1, 8, 14, 4, 56, 434, DateTimeKind.Utc).AddTicks(6021),
                            District = "Марьино",
                            Email = "dima@example.com",
                            ExperienceYears = 3,
                            FirstName = "Дмитрий",
                            LastName = "Кузнецов",
                            Latitude = 55.6494,
                            Longitude = 37.743000000000002,
                            Phone = "+79162345678",
                            Rating = 4.6m,
                            RepeatOrdersCount = 12,
                            ReviewsCount = 28,
                            Slug = "dima-dogwalker",
                            UserId = new Guid("6fbf4dc8-cf8b-46df-960f-b6d0c6eb7ff9")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            City = "Санкт-Петербург",
                            CompletedOrdersCount = 112,
                            CreatedAt = new DateTime(2025, 9, 8, 14, 4, 56, 434, DateTimeKind.Utc).AddTicks(6025),
                            District = "Центральный",
                            Email = "maria@example.com",
                            ExperienceYears = 7,
                            FirstName = "Мария",
                            LastName = "Попова",
                            Latitude = 59.938600000000001,
                            Longitude = 30.3141,
                            Phone = "+79213456789",
                            Rating = 4.9m,
                            RepeatOrdersCount = 35,
                            ReviewsCount = 67,
                            Slug = "maria-grooming",
                            UserId = new Guid("ad0ec355-8d4f-4e96-9663-d497cb48a47a")
                        });
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarAvailabilityWindowEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", "Calendar")
                        .WithMany("AvailabilityWindows")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarBookedSlotEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", "Calendar")
                        .WithMany("BookedSlots")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarBookingSettingsEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", "Calendar")
                        .WithOne("BookingSettings")
                        .HasForeignKey("Tailly.SpecialistService.Core.Entities.Calendar.CalendarBookingSettingsEntity", "CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarDayOverrideEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", "Calendar")
                        .WithMany("DayOverrides")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", "Specialist")
                        .WithOne("Calendar")
                        .HasForeignKey("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", "SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", "Specialist")
                        .WithOne("Details")
                        .HasForeignKey("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", "SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.PetAgeEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", "Details")
                        .WithMany("PetAges")
                        .HasForeignKey("DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.PetSizeEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", "Details")
                        .WithMany("PetSizes")
                        .HasForeignKey("DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.PetTypeEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", "Details")
                        .WithMany("PetTypes")
                        .HasForeignKey("DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Gallery.SpecialistGalleryEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", "Specialist")
                        .WithMany("SpecialistGallery")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Reviews.ReviewEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", "Specialist")
                        .WithMany("Reviews")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Services.ServiceEntity", b =>
                {
                    b.HasOne("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", "Specialist")
                        .WithMany("Services")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Calendar.CalendarEntity", b =>
                {
                    b.Navigation("AvailabilityWindows");

                    b.Navigation("BookedSlots");

                    b.Navigation("BookingSettings");

                    b.Navigation("DayOverrides");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Details.DetailsEntity", b =>
                {
                    b.Navigation("PetAges");

                    b.Navigation("PetSizes");

                    b.Navigation("PetTypes");
                });

            modelBuilder.Entity("Tailly.SpecialistService.Core.Entities.Specialist.SpecialistEntity", b =>
                {
                    b.Navigation("Calendar");

                    b.Navigation("Details");

                    b.Navigation("Reviews");

                    b.Navigation("Services");

                    b.Navigation("SpecialistGallery");
                });
#pragma warning restore 612, 618
        }
    }
}
